#!/bin/sh
# Xcode Cloud pre-build script
#
# Generates TVSharedLists/Secrets.swift and patches Info.plist
# from environment variables set in the Xcode Cloud workflow.
#
# Required secrets (Xcode Cloud → Workflow → Environment → Secrets):
#   ADMOB_APP_ID     ← AdMob App ID  (ca-app-pub-XXXXXXXXXXXXXXXX~XXXXXXXXXX)
#   ADMOB_BANNER_ID  ← Banner ad unit ID (ca-app-pub-XXXXXXXXXXXXXXXX/XXXXXXXXXX)

set -e

SECRETS_FILE="$CI_WORKSPACE/TVSharedLists/TVSharedLists/Secrets.swift"
INFO_PLIST="$CI_WORKSPACE/TVSharedLists/TVSharedLists/Info.plist"

# ── Validate required variables ────────────────────────────────────────────
MISSING=""
for VAR in ADMOB_APP_ID ADMOB_BANNER_ID; do
    eval VALUE=\$$VAR
    if [ -z "$VALUE" ]; then
        MISSING="$MISSING $VAR"
    fi
done

if [ -n "$MISSING" ]; then
    echo "ERROR: Missing required environment variables:$MISSING"
    echo "Set them in Xcode Cloud → Workflow → Environment → Secrets."
    exit 1
fi

# ── Generate Secrets.swift ─────────────────────────────────────────────────
cat > "$SECRETS_FILE" << SWIFT
// Auto-generated by ci_pre_xcodebuild.sh — do not edit
enum AdSecrets {
    static let gadAppID       = "${ADMOB_APP_ID}"
    static let bannerAdUnitID = "${ADMOB_BANNER_ID}"
}
SWIFT

echo "Secrets.swift generated."

# ── Patch GADApplicationIdentifier in Info.plist ───────────────────────────
/usr/libexec/PlistBuddy \
    -c "Set :GADApplicationIdentifier ${ADMOB_APP_ID}" \
    "$INFO_PLIST"

echo "Info.plist GADApplicationIdentifier patched."
